version: '3.8.2'

services:
    app:
        build: ./
        command: streamlit run app/streamlit_app.py --server.port 8501
        volumes:
            - ./:/project/app
        ports:
            - 8501:8501
        image:  streamlit_at3:12